export const STATES = {
  SITTING: 0,
  RUNNING: 1,
  JUMPING: 2,
  FALLING: 3
}

export const STATE_NAMES = {
  SITTING: 'SITTING',
  RUNNING: 'RUNNING',
  JUMPING: 'JUMPING',
  FALLING: 'FALLING',
}
